// Generated by https://quicktype.io

export interface AuthResponse {
  token: string;
  user: User;
}

export interface User {
  id: string;
  storeId: string;
  firstName: string;
  lastName: string | null;
  email: string;
  phone: string | null;
  avatarUrl: string | null;
  isShopOwner: boolean;
  isActive: boolean;
  role: string;
}
