// Generated by https://quicktype.io

import type { Category } from './category.interface';

export interface CategoriesResponse {
  meta: Meta;
  results: Category[];
}

export interface Meta {
  totalItems: number;
  currentPage: number;
  pageSize: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
}
