// Generated by https://quicktype.io

import type { Customer } from './customer.interface';

export interface CustomersResponse {
  meta: Meta;
  results: Customer[];
}

export interface Meta {
  totalItems: number;
  currentPage: number;
  pageSize: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
}
